environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform

test_script:
  - node --version
  - npm --version
